### ISSUE TITLE
Which parameter in the config is the Chunk Length L in the Paper

### ISSUE THREAD

**Issue by desires19** [MTLab/MorphMLP#1]
Excuse me 
Thanks for your excellent work MorphMLP, which inspire me a lot.
In the paper ***MorphMLP: An Efficient MLP-Like Backbone for Spatial-Temporal Representation Learning,*** the Hyperparameter chunk length ***L*** is follow the range[14, 28, 28, 49] in different stage.
However, I can't find it in your code. the ***_C.MORPH.SEGMENT_DIM*** seems like the Hyperparameter D[https://github.com/MTLab/MorphMLP/blob/aa59826aa2/slowfast/config/defaults.py#:~:text=_C.MORPH.SEGMENT_DIM%20%3D%20%5B32%2C%2016%2C%2016%2C%2016%5D](url)
Could you help me find the Chunk Lenght ***L***?
Thanks you!

**Comment by junhaozhang98** [comment]
Thanks for your question.

The range [14,28,28,49] is in here. https://github.com/MTLab/MorphMLP/blob/aa59826aa2d5cdd493267f9ede6d5433d3527e87/configs/K400/K400_MLP_B32x4.yaml#L24

**Comment by desires19** [comment]
Thanks for your answer!
Bset wish to you!
