### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Grit1024** [MTLab/MorphMLP#2]
Hi！
I would like to ask what is the specific meaning of **x=self.patch_embed1(x[0])**, and shouldn’t the input of the **conv_3xnxn** part be 5-dimensional, so I can’t run it successfully. it is located in **morphmlp. py**.
Thank you!

**Comment by junhaozhang98** [comment]
Thanks for your question.

x[0] have a dimension B, C, T, H, W.  

we adopt the slowfast codebase,  which usually converts the frames to[ a list x during dataset processing](https://github.com/MTLab/MorphMLP/blob/3eb34c778b0995b044abd908082468fab9118757/slowfast/datasets/kinetics.py#L311). 
https://github.com/MTLab/MorphMLP/blob/3eb34c778b0995b044abd908082468fab9118757/slowfast/datasets/kinetics.py#L311
So we use x[0] to extract the all frames in the list.

**Comment by Grit1024** [comment]
Thank you for your reply. 
I currently use my own data instead of kinetics and somethingsomething. In **def forward_ Features (self, x):**, In my understanding, **x [0]** is similar to a slice operation. It is passed in (B C T H W) and becomes (C T H W), so in **patch_ In embed1**, I encountered the problem of 3D convolution operation: **Expected 5-dimensional input for 5-dimensional weight [56, 3, 3, 3, 3], but got 4-dimensional input of size**. I am not sure whether it is the same as you said. In addition, I do not currently use the slowfast sampling strategy, but similar to the dense sampling input data.

**Comment by junhaozhang98** [comment]
In our code, x has a dimension [tensor(B,C,T,H,W)] (a list) and x[0] has a dimension tensor(B,C,T,H,W).

For your own purpose, since the dimension of  your input has been already tensor(B,C,T,H,W), you do not need to use x[0]. You should make sure that  the dimension of input to patch embedding  is (B,C,T,H,W), which means that you are supposed to adopt x[0] to x.

**Comment by Grit1024** [comment]
In fact, I have tried this operation, but there are still some problems. Maybe I should understand the specific principle again. 
Anyway, thank you for your timely reply, this is a great research!

**Comment by junhaozhang98** [comment]
The code is designed for the input with dimension (B,3,16,224,224)-morphmlp.py or (B,3,32,224,224)-morphmlp32.py. For other dimension, you may need to add additonal padding when pass it into FC layer.

**Comment by Grit1024** [comment]
I actually tried to input (B, 3, 32, 96, 96), but in MorphFC_ An error similar to shape '[32, 16, 41, 14, 14, 8]' is invalid for input of size 33030144 appears in S or T. In addition, does the change of image size lead to the unavailability of the pre-training weight.

**Comment by junhaozhang98** [comment]
You should add additonal paddings to make sure that the resolutions of feature map in each layer can be  divisible by corresponding segment dimension(chunk length).

**Comment by Grit1024** [comment]
Sorry, I don't quite understand what extra padding you mean?Do I need to change the image to 224 or change something else, I tried segment_dim and embed_dims and it doesn't seem to be relevant...

**Comment by junhaozhang98** [comment]
For example, in the forward process of Morph_S  or Morph_T,  you should make H*W divisible by (tmp=segment_dim) so you need  to add paddings to H or W or T. I recommend you to observe the shape of each layer output, using (B,3,16,224,224) as input. 
https://github.com/MTLab/MorphMLP/blob/3eb34c778b0995b044abd908082468fab9118757/slowfast/models/morphmlp.py#L97

**Comment by Grit1024** [comment]
Thank you very much！
I can currently enter my data and run normally, since the image size is smaller, does this mean that I cannot currently use imagenet pre-trained weights directly? 
Another question is about the role of the t_stride parameter in it. The specific performance is...
