### ISSUE TITLE
The pretrain model of MorphMLP-S maybe wrong.

### ISSUE THREAD

**Issue by leexinhao** [MTLab/MorphMLP#4]
In your paper the stages of MorphMLP-S is [3, 4, 9, 3] but in the `mlp_s16x4_k400.pth` and `video_morphmlp_s.pth` which is [4, 6, 15, 4], is it something wrong?

**Comment by junhaozhang98** [comment]
Hi, thanks for your question. It seems that [4,6,15,4] is our MorphMlP-B. I have re-uploaded MorphMLP-S checkpoints to google drive and baiduyun. Please check it.
